### ISSUE TITLE
Broken links in the Dashboard

### ISSUE THREAD

**Issue by githubyouser** [biblicalhumanities/biblicalhumanities.github.io#2]
Mounce's Lexicon should be: https://github.com/jcuenod/dictionary

Also, the Lace (hOCR) link is broken. Updated Github seems to be [here](https://github.com/brobertson/Lace2), but that [site](http://trylace.org/) is down too. :(

**Comment by biblenerd** [comment]
I made a pull request (pending merge) with fixed links: https://github.com/biblicalhumanities/biblicalhumanities.github.io/pull/3
